<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>robot_bringup</name>
  <version>0.0.0</version>
  <description>Real robot bringup launch and configuration.</description>
  <maintainer email="1270161395@qq.com">ubuntu</maintainer>
  <license>TODO: License declaration</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>controller</exec_depend>
  <exec_depend>action_msgs</exec_depend>
  <exec_depend>cartographer_ros</exec_depend>
  <exec_depend>exploration</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>imu_cartographer_publisher</exec_depend>
  <exec_depend>nav_msgs</exec_depend>
  <exec_depend>nav2_bringup</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>peripherals</exec_depend>
  <exec_depend>rf2o_laser_odometry</exec_depend>
  <exec_depend>robot_description</exec_depend>
  <exec_depend>robot_localization</exec_depend>
  <exec_depend>ros_robot_controller</exec_depend>
  <exec_depend>rplidar_ros</exec_depend>
  <exec_depend>rviz2</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
